name: Build and Release

on:
  push:
    branches:
      - mac
      - master
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win32
          - os: macos-latest
            platform: darwin
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run make
        
      - name: Build (macOS)
        if: matrix.os == 'macos-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 不进行macOS应用签名和公证
        run: npm run make
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: out/make/
          
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' || contains(github.ref, 'refs/heads/')
    
    steps:
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-win32
          path: ./artifacts/win32/
          
      - name: Download macOS Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-darwin
          path: ./artifacts/darwin/
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ./artifacts/**/*