name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win32
          - os: macos-latest
            platform: darwin
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run make
        
      - name: Build (macOS Intel)
        if: matrix.os == 'macos-latest' && matrix.arch == 'x64'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_target_arch: x64
        run: npm run make
        
      - name: Build (macOS Apple Silicon)
        if: matrix.os == 'macos-latest' && matrix.arch == 'arm64'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_target_arch: arm64
        run: npm run make
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }}
          path: out/make/
          
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' || contains(github.ref, 'refs/heads/')
    
    steps:
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-win32
          path: ./artifacts/win32/
          
      - name: Download macOS Intel Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-darwin-x64
          path: ./artifacts/darwin-x64/
          
      - name: Download macOS Apple Silicon Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-darwin-arm64
          path: ./artifacts/darwin-arm64/
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          generate_release_notes: true
          files: |
            ./artifacts/**/*